config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users, only: %i[sessions registrations passwords]

  resources :users, only: %i[show], param: :username
  get "edit_profile", to: "users#edit"
  patch "profile", to: "users#update"

  resources :posts, only: %i[index show new create]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates  :body, presence: true

  has_rich_text :body
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :post_id, uniqueness: { scope: :user_id, message: "Post já está curtido" }
end

app/models/post.rb
class Post < ApplicationRecord
  validates :description, presence: true

  belongs_to :created_by, class_name: "User"

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :photo
  validates :photo, attached: true, 
    content_type: %i[png jpg jpeg],
    size: { less_than: 5.megabytes }

  def liked_by?(user)
    likes.where(user: user).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :username, presence: true
  validates :username, uniqueness: true

  has_many :posts, foreign_key: :created_by_id, dependent: :destroy
  has_many :likes
  has_many :comments

  has_one_attached :avatar
  validates :avatar, content_type: %i[png jpg jpeg]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  private
  def layout_by_resource
    "authentication.html.erb" if devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up, keys: %i[name username]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      CommentChannel.broadcast_to "comment_channel",
        post_id: @comment.post_id,
        comment_created: render_to_string(partial: @comment)

      redirect_to @comment.post, notice: "Comentário enviado com sucesso."
    else
      @post = @comment.post
      flash.now[:alert] = @comment.errors.full_messages.to_sentence
      render "posts/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:post_id, :body)
  end
end

app/controllers/concerns/suggested_users.rb
module SuggestedUsers
  extend ActiveSupport::Concern

  private
  def set_suggested_users
    @suggested_users = User.all - [current_user]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[destroy]

  def create
    like = current_user.likes.build(like_params)

    if like.save
      render json: { successful: true, id: like.id }
    else
      render json: { successful: false }
    end
  end

  def destroy
    render json: { successful: @like.destroy }
  end

  private

  def set_like
    @like = current_user.likes.find(params[:id])
  end

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SuggestedUsers

  before_action :set_post, only: %i[show]
  before_action :set_suggested_users, only: %i[index]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(created_by: current_user))

    if @post.save
      PostChannel.broadcast_to "post_channel", post_created: render_to_string(partial: @post)
      redirect_to @post, notice: 'Post foi criado com sucesso.'
    else
      flash.now[:alert] = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:photo, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SuggestedUsers

  before_action :set_suggested_users, only: %i[show]

  def show
    user = User.find_by(username: params[:username])
    @posts = user.posts

    render "posts/index"
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: "Seu perfil foi atualizado com sucesso."
    else
      flash[:alert] = current_user.errors.full_messages.to_sentence
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
  def embedded_svg(path)
    File.open("app/assets/images/#{path}", "rb") { |file| raw(file.read) }
  end

  def user_avatar(user)
    if user.avatar.attached?
      avatar = user.avatar.variant(combine_options: { resize: '100x100^', extent: '100x100' })
    else
      avatar = "default-avatar.jpg"
    end
    image_tag avatar, class: "photo"
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class="comment">
  <%= link_to user_path(comment.user.username), class: "avatar" do %>
    <%= user_avatar(comment.user) %>
  <% end %>

  <section class="body">
    <strong><%= comment.user.username %></strong> <%= comment.body %>
  </section>

  <section class="created-at">
    <%= time_ago_in_words(comment.created_at) %> atrás
  </section>
</div>

app/views/layouts/_user_actions_modal.html.erb
<div id="user-actions" class="modal">
  <div class="user-action">
    <%= link_to "Editar seu perfil", edit_profile_path %>
  </div>

  <div class="user-action">
    <%= link_to "Deslogar", destroy_user_session_path, method: :delete,
      data: { confirm: "Desligar da sua conta?"} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application'%>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body data-flash-messages="<%= JSON.dump(flash.to_a) %>">
    <header>
      <div class='container'>
        <nav>
          <div class='logo-icon'>
            <%= link_to embedded_svg("instagram-icon.svg"), root_path %>
          </div>

          <div class='logo-icon'>
            <%= link_to root_path do %>
              <%= image_tag "instagram.png" %>
            <% end %>
          </div>
        </nav>

        <nav class='actions'>
          <%= link_to embedded_svg("plus.svg"), new_post_path %>
          <%= link_to embedded_svg("user.svg"), "#", data: { modal_id: "user-actions" } %>
        </nav>
      </div>
    </header>

    <%= yield %>

    <%= render "layouts/user_actions_modal"%>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Autenticação - Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'authentication'%>
    <%= javascript_pack_tag 'authentication' %>
  </head>

  <body data-flash-messages="<%= JSON.dump(flash.to_a) %>">
    <main>
      <section class="hero">
        <div class="logo">
          <%= image_tag "instagram.png" %>
        </div>
        <%= yield %>
      </section>
    </main>
  </body>
</html>

app/views/likes/_like.html.erb
<div class="action" data-post-id="<%= post.id %>"
  data-like-id="<%= post.likes.find_by(user: current_user)&.id %>"
>
  <div class="like <%= post.liked_by?(current_user) ? "hidden" : "" %>">
    <%= embedded_svg "like.svg" %>
  </div>

  <div class="dislike <%= post.liked_by?(current_user) ? "" : "hidden" %>">
    <%= embedded_svg "liked.svg" %>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, class: "new-post") do |form| %>
  <h1>Novo post</h1>

  <div class="field">
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.text_field :description, placeholder: "Descrição" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <header>
    <nav>
      <%= user_avatar(post.created_by) %>
      <h4><%= post.created_by.username %></h4>
    </nav>

    <nav class="actions">
      <div class="actions">
        <%= embedded_svg "options.svg" %>
      </div>
    </nav>
  </header>

  <section class="image">
    <%= image_tag post.photo %>
  </section>

  <div class="details">
    <section class="actions">
      <nav>
        <%= render "likes/like", post: post %>

        <div class="action">
          <%= link_to post do%>
            <%= embedded_svg "comment.svg" %>
          <% end %>
        </div>

        <div class="action">
          <%= embedded_svg "share.svg" %>
        </div>
      </nav>

      <nav>
        <div class="action">
          <%= embedded_svg "save.svg" %>
        </div>
      </nav>
    </section>

    <section class="description">
      <p><strong><%= post.created_by.username %></strong> <%= post.description %></p>
    </section>

    <section class="created-at">
      <%= time_ago_in_words(post.created_at) %> atrás
    </section>
  </div>
</article>

app/views/posts/index.html.erb
<main class="posts-page container">
  <section class="posts">
    <% if @posts.any? %>
      <%= render @posts %>
    <% else %>
      Nenhum post ainda.
    <% end %>
  </section>

  <aside>
    <%= render current_user %>

    <section class="suggestions">
      <h4>Sugestões Para Você</h4>

      <%= render @suggested_users %>
    </section>
  </aside>


  <footer>
    © <%= Date.current.year %>  INSTAGRAM CLONE
  </footer>
</main>

app/views/posts/new.html.erb
<main class="container">
    <%= render "form", post: @post %>
</main>

app/views/posts/show.html.erb
<main class="posts-page has-comments container">
  <section class="posts">
    <%= render @post %>
  </section>

  <aside>
    <section class="comments" data-post-id="<%= @post.id %>">
      <% if @post.comments.any? %>
        <%= render @post.comments %>
      <% else %>
        Nenhum comentário ainda.
      <% end %>

      <%= form_with model: @comment, local: true, class: "new-comment" do |form| %>
        <%= form.hidden_field :post_id, value: @post.id %>

        <div class="field">
          <%= form.rich_text_area :body, placeholder: "Comentário", require: true %>
        </div>

        <div class="actions">
          <%= form.submit "Enviar comentário" %>
        </div>

      <% end %>

    </section>
  </aside>

</main>

app/views/users/_user.html.erb
<%= link_to user_path(user.username), class: "profile" do %>

  <%= user_avatar(user) %>

  <h5 class="username"><%= user.username%></h5>
  <p class="full-name"><%= user.name%></p>
<% end %>

app/views/users/edit.html.erb
<main class="container">
  <%= form_with model: current_user, url: profile_path, local: true, class: "edit-profile" do |form| %>
    <h1>Editar seu perfil</h1>

    <div class="field">
      <%= form.file_field :avatar %>
    </div>

    <div class="field">
      <%= form.text_field :name, placeholder: "Nome" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</main>